name: Claude Code Review

on:
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@claude review')
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Automated review prompt for ZKP2P Client SDK (TypeScript SDK)
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.issue.number }}
            
            Please review this pull request for the ZKP2P Client SDK.
            
            This is a TypeScript SDK for integrating ZKP2P functionality into applications.
            It's structured as a monorepo with packages for different platforms.
            
            Focus on:
            - SDK design patterns and API ergonomics
            - TypeScript type safety and proper typing
            - Browser and Node.js compatibility
            - Error handling and developer experience
            - Documentation completeness and clarity
            - Package structure and exports configuration
            - Semantic versioning considerations
            - Test coverage for SDK methods
            - Bundle size and tree-shaking support
            - Cross-platform compatibility (web, mobile, node)
            - Smart contract interaction abstractions
            - Proper async/await patterns and promise handling
            
            The project uses npm as its package manager. Be constructive and helpful in your feedback.
            
            IMPORTANT: Post your review as a GitHub comment using `gh pr comment` or the MCP GitHub comment tools.
            Only your GitHub comments that you post will be seen, so don't submit your review as a normal message, just as comments.
            If you want to use sticky comments to update the same comment on subsequent reviews, use the MCP tool: mcp__github_comment__update_claude_comment
          
          # Use Claude Opus 4 for comprehensive code reviews with ability to post comments
          claude_args: |
            --model claude-opus-4-1-20250805
            --max-turns 10
            --allowedTools "mcp__github_comment__update_claude_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(npm test),Bash(npm run lint),Bash(npm run build)"